### ISSUE TITLE
include original crate's version

### ISSUE THREAD

**Issue by xxchan** [madsim-rs/madsim#145]
e.g., `0.2.17+aws-sdk-s3.0.21` or `0.2.17+0.21`

Other examples:
- zstd `version = "0.12.3+zstd.1.5.2`
- rdkafka-sys `version = "4.3.0+1.9.2`

This is called "Build metadata" in semver: https://semver.org/spec/v2.0.0.html#spec-item-10

**Comment by wangrunji0408** [comment]
Good idea. Will change to this style from next version.

**Comment by xxchan** [comment]
I'm now wondering whether we should do a major version bump when we update the (major) version of the original crate, e.g., #147. 😇

**Comment by xxchan** [comment]
.. Otherwise people may unexpectedly have breaking changes, unless they use precise version of madsim 😇

**Comment by wangrunji0408** [comment]
According to [semver](https://semver.org/spec/v2.0.0.html#spec-item-10):
> Build metadata MUST be ignored when determining version precedence.

Therefore we should bump a major version if the original crate bumps.

**Comment by xxchan** [comment]
The benefit of letting all sub-crates with the same version like `arrow-*`:
- easy for maintainers to release new versions.
- easy for users to know which crates can work together.

It seems such policy isn't too common in the ecosystem. e.g., `tokio-*` has different versions.

I think arrow is also special because the crates are highly related and are basic building blocks (maybe except things like flight...), so it's natural to update them all at once.

For tokio/madsim, it makes less sense to update all things together. e.g., update `tokio-utils` without updating `tokio`, and update `madsim-tonic` without updating `madsim` and `madsim-s3`. 

.. But it might be OK to require users to update all `tokio-*` after `tokio` bumps major version.

.... But for madsim it might be more problematic, since each `madsim-*` is a relatively critical dependency. 🤔️  Ideally, each `madsim-*` can work with multiple major versions of `madsim`, like icelake can [work with multiple major versions of arrow](https://github.com/icelake-io/icelake/blob/2ebe59821f358ed8a80f541d2bf5256974b372ad/Cargo.toml#L19-L20). But of course that brings maintenance burden.

**Comment by wangrunji0408** [comment]
I prefer not to maintain the same version because each `madsim-*` is a mock of external crate. We don't have control of these crates. If we keep the same version, every version bump from external crate (such as tonic 0.8 -> 0.9) will force a bump of madsim ecosystem. This is weird. 🤪

**Comment by wangrunji0408** [comment]
When using `madsim-*`, users have to be aware of both madsim version and the original crate version. Because:
1. All madsim dependencies must be compatible, otherwise there will be multiple async runtime. (similar to the situation of tokio 0.1, 0.3, 1)
2. In normal build, users are actually using the original crate, e.g. `tonic`, even if they see `madsim-tonic`.

So it is ideal to have both versions in the metadata:
```
madsim-tonic 0.3.0+madsim.0.2+tonic.0.9
```

But it looks a little verbose. Maybe omitting the madsim version is also fine.
```
madsim-tonic 0.3.0+0.9
```

**Comment by xxchan** [comment]
Yes I think generally we are in the same page. The last thing is that maybe `+0.9` can also be ignored, as it's known in the dependency tree. 😇
