### ISSUE TITLE
patch `tokio_stream`

### ISSUE THREAD

**Issue by BugenZhao** [madsim-rs/madsim#185]
I've encountered type mismatching when using `opentelemetry` with `madsim`:

https://github.com/risingwavelabs/risingwave/pull/13443#issuecomment-1813892645

It appears that we may need to patch `tokio_stream` to resolve this.

**Comment by wangrunji0408** [comment]
We have this patch. It's in another repo. https://github.com/madsim-rs/tokio/tree/madsim
This problem seems to be caused by the tokio inside opentelemetry, which we can't patch. 🥵
