### ISSUE TITLE
Implement `tokio::task::AbortHandle::is_finished`

### ISSUE THREAD

**Issue by tomasol** [madsim-rs/madsim#191]
I would like to see `is_finished` implemented on `madsim::task::AbortHandle` mirroring the [original function](https://docs.rs/tokio/latest/tokio/task/struct.AbortHandle.html#method.is_finished)

**Comment by wangrunji0408** [comment]
Thanks for your feedback. We will add this method soon.

**Comment by tomasol** [comment]
@wangrunji0408  Awesome, thanks for the quick patch and a great project!
