### ISSUE TITLE
Creating multiple runtimes with the same seed yields different random values

### ISSUE THREAD

**Issue by tomasol** [madsim-rs/madsim#201]
Steps to reproduce:
Sequentially create multiple runtimes from `madsim::runtime::Builder` with the same seed
Print `getrandom::getrandom` in each simulation

The first value is different, then all other values are the the same, e.g. 
```
[114]
[139]
[139]
[139]
...
```

[Reproducer](https://github.com/tomasol/madsim-getrandom-reproducer)

**Comment by wangrunji0408** [comment]
Hi, thanks for your feedback! We have fixed this bug and released a new version 0.2.27.

**Comment by tomasol** [comment]
Great, thanks. I found this issue while I was verifying determinism manually, but I will create a follow-up issue for it.
