### ISSUE TITLE
Allow toggling off the new-thread-spawned detector

### ISSUE THREAD

**Issue by tomasol** [madsim-rs/madsim#210]
When a test spawns a new thread, madsim will panic with "attempt to spawn a system thread in simulation.", which is good for catching one specific kind of determinism breakage.
However I still see benefits of using madsim's seeded RNG with regular tests, as it helps narrowing down the possible causes of a failure, especially for property-based testing. I would like to propose adding a new environment variable that would disable the said check.

I am currently testing with the check removed, I also had to insert a `sleep` if `going == false` in the [block_on](https://github.com/madsim-rs/madsim/blob/bb6d6d9cbdcd58890c80e90c832f29cf2ed720fb/madsim/src/sim/task/mod.rs#L242) loop.

**Comment by tomasol** [comment]
Thanks for the quick fix again :heart: , there is just one more thing that I mentioned on the last line that enables awaiting on events triggered by the thread.

**Comment by wangrunji0408** [comment]
Oh sorry I missed the last part. Thanks for your PR!
