### ISSUE TITLE
Encountered `there is no reactor running, must be called from the context of a Madsim runtime` while spawning task in `drop` impl

### ISSUE THREAD

**Issue by kwannoel** [madsim-rs/madsim#228]
I encountered the following error message in this branch: https://github.com/risingwavelabs/risingwave/pull/18795, in its [main-cron ci workflow](https://buildkite.com/risingwavelabs/main-cron/builds/3472#01926551-5f93-4428-8b5a-847d3cb15cc2).

[recovery-streaming-4.log](https://github.com/user-attachments/files/17275470/recovery-streaming-4.log)

This happens when running a [forked version of sqlx](https://github.com/kwannoel/sqlx/tree/madsim) with `madsim-tokio 0.2.30` as its dependency, to override `tokio`.

```
thread '<unnamed>' panicked at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.30/src/sim/runtime/context.rs:27:44:
there is no reactor running, must be called from the context of a Madsim runtime
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/option.rs:2030:5
   4: expect<alloc::sync::Arc<madsim::sim::task::TaskInfo, alloc::alloc::Global>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/option.rs:933:21
   5: {closure#0}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.30/src/sim/runtime/context.rs:27:44
   6: try_with<core::cell::RefCell<core::option::Option<alloc::sync::Arc<madsim::sim::task::TaskInfo, alloc::alloc::Global>>>, madsim::sim::runtime::context::current_task::{closure_env#0}, alloc::sync::Arc<madsim::sim::task::TaskInfo, alloc::alloc::Global>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/std/src/thread/local.rs:283:12
   7: with<core::cell::RefCell<core::option::Option<alloc::sync::Arc<madsim::sim::task::TaskInfo, alloc::alloc::Global>>>, madsim::sim::runtime::context::current_task::{closure_env#0}, alloc::sync::Arc<madsim::sim::task::TaskInfo, alloc::alloc::Global>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/std/src/thread/local.rs:260:9
   8: current_task
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.30/src/sim/runtime/context.rs:27:10
   9: current
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.30/src/sim/task/mod.rs:586:20
  10: spawn<sqlx_core::pool::connection::{impl#5}::return_to_pool::{async_block_env#1}<sqlx_sqlite::database::Sqlite>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.30/src/sim/task/mod.rs:664:5
  11: spawn<sqlx_core::pool::connection::{impl#5}::return_to_pool::{async_block_env#1}<sqlx_sqlite::database::Sqlite>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-tokio-0.2.30/src/sim/runtime.rs:152:9
  12: spawn<sqlx_core::pool::connection::{impl#5}::return_to_pool::{async_block_env#1}<sqlx_sqlite::database::Sqlite>>
             at ./.cargo/git/checkouts/sqlx-89fb48fb6611e438-shallow/15ee4ba/sqlx-core/src/rt/mod.rs:68:41
  13: drop<sqlx_sqlite::database::Sqlite>
             at ./.cargo/git/checkouts/sqlx-89fb48fb6611e438-shallow/15ee4ba/sqlx-core/src/pool/connection.rs:169:13
  14: drop_in_place<sqlx_core::pool::connection::PoolConnection<sqlx_sqlite::database::Sqlite>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/ptr/mod.rs:542:1
  15: drop_in_place<sea_orm::database::db_connection::InnerConnection>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/ptr/mod.rs:542:1
  16: drop_in_place<core::cell::UnsafeCell<sea_orm::database::db_connection::InnerConnection>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/ptr/mod.rs:542:1
  17: drop_in_place<futures_util::lock::mutex::Mutex<sea_orm::database::db_connection::InnerConnection>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/ptr/mod.rs:542:1
  18: drop_slow<futures_util::lock::mutex::Mutex<sea_orm::database::db_connection::InnerConnection>, alloc::alloc::Global>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/alloc/src/sync.rs:1844:18
  19: drop<futures_util::lock::mutex::Mutex<sea_orm::database::db_connection::InnerConnection>, alloc::alloc::Global>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/alloc/src/sync.rs:2531:13
  20: drop_in_place<alloc::sync::Arc<futures_util::lock::mutex::Mutex<sea_orm::database::db_connection::InnerConnection>, alloc::alloc::Global>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/ptr/mod.rs:542:1
...
```

The origin of the panic is here: https://github.com/kwannoel/sqlx/blob/15ee4ba0eedc269540e42c6b4437c10de7325ed7/sqlx-core/src/pool/connection.rs#L166-L171:

```
impl<DB: Database> Drop for PoolConnection<DB> {
    fn drop(&mut self) {
        // We still need to spawn a task to maintain `min_connections`.
        if self.live.is_some() || self.pool.options.min_connections > 0 {
            crate::rt::spawn(self.return_to_pool());
        }
    }
}
```

This calls `rt::spawn` https://github.com/kwannoel/sqlx/blob/15ee4ba0eedc269540e42c6b4437c10de7325ed7/sqlx-core/src/rt/mod.rs#L61-L78:
```
pub fn spawn<F>(fut: F) -> JoinHandle<F::Output>
where
    F: Future + Send + 'static,
    F::Output: Send + 'static,
{
    #[cfg(feature = "_rt-tokio")]
    if let Ok(handle) = tokio::runtime::Handle::try_current() {
        return JoinHandle::Tokio(handle.spawn(fut)); // <----------- Panics here.
    }


    #[cfg(feature = "_rt-async-std")]
    {
        return JoinHandle::AsyncStd(async_std::task::spawn(fut));
    }


    #[cfg(not(feature = "_rt-async-std"))]
    missing_rt(fut)
}
```

That calls: https://github.com/madsim-rs/madsim/blob/b7dbec004a161bb7c98b7d3a728a0c0739c1a6fb/madsim/src/sim/task/mod.rs#L658-L665

Which calls: https://github.com/madsim-rs/madsim/blob/b7dbec004a161bb7c98b7d3a728a0c0739c1a6fb/madsim/src/sim/task/mod.rs#L585-L592

And finally calls: https://github.com/madsim-rs/madsim/blob/b7dbec004a161bb7c98b7d3a728a0c0739c1a6fb/madsim/src/sim/runtime/context.rs#L26-L28

It then panics, since there's no current task.

My modification of `try_current` did not manage to fix it https://github.com/madsim-rs/madsim/pull/227/. Even if we modified `try_current` to properly check the task context, it will still be missing and just return an error instead of panicking. So we will be unable to spawn a thread to run the future still.

I realize it's quite similar to existing issues in madsim, specifically when spawn is called during a `drop`, similar to https://github.com/madsim-rs/madsim/issues/182. So I'm trying to understand if this is a known problem, and if so, what is the exact root cause.

Reproducible example: https://github.com/madsim-rs/madsim/pull/229

A list of related issues I found:
- https://github.com/madsim-rs/madsim/issues/179
- https://github.com/madsim-rs/madsim/issues/182
- https://github.com/madsim-rs/madsim/issues/213

Thanks in advance for your advice 🙏

**Comment by fuyufjh** [comment]
This seems to be the most related explanation:  https://github.com/madsim-rs/madsim/issues/182#issuecomment-1809931396

> The reason of this panic is that madsim needs to know which node is `spawn`ing the task. But when a task is dropping, the global context is empty. In other words, madsim doesn't run any task at that time, so it can't know who is spawning the task. This seems to be a bug since this behavior is normal on tokio. But I don't have a clear solution yet.

As the bug only happens in `drop()`, I guess the `Handler` or some context is incorrectly dropped before **our** `drop()`.

**Comment by fuyufjh** [comment]
Kindly ask for assistance from the project author @wangrunji0408

**Comment by kwannoel** [comment]
```
2022-04-16T11:16:45.000000Z  INFO madsim::sim::runtime::context: enter task with system thread: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO node{id=0 name="main"}:task{id=0}: madsim::sim::task: system thread of run_all_ready begin: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO node{id=0 name="main"}:task{id=0}: madsim_tokio::sim::runtime::tests: system thread of t1: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO node{id=0 name="main"}:task{id=0}: madsim::sim::runtime::context: system thread of current_task: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO node{id=0 name="main"}:task{id=0}: madsim::sim::runtime::context: drop task: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO madsim::sim::task: system thread of run_all_ready done: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO madsim_tokio::sim::runtime::tests: system thread of t3 drop: ThreadId(2)
2022-04-16T11:16:45.000000Z  INFO madsim::sim::runtime::context: system thread of current_task: ThreadId(2)
```

After doing some tracing, here's some further finding. The dropped task does not run on any executor node. Therefore it does not enter the task context, and we get "no runtime" error. Will continue investigating.

(A side note, perhaps we can make the error messages more specific, rather than no runtime, we can say "task context not found", but perhaps this is inconsistent with tokio's errors.)

**Comment by kwannoel** [comment]
In relation to this specific testcase:
```
    fn runtime_drop_and_spawn_struct_fail_with_try_current_task() {
        init_logger();

        #[derive(Debug)]
        struct A {}
        impl Drop for A {
            fn drop(&mut self) {
                let bt = Backtrace::force_capture();
                tracing::info!("backtrace of t3 drop: {:#?}", bt);
                tracing::info!("system thread of t3 drop: {:?}", std::thread::current().id());
                if let Some(handle) = Handle::try_current().ok() {
                    handle.spawn(async {
                        std::future::pending::<()>().await
                    });
                }
            }
        }

        let a = A {};
        let runtime = madsim::runtime::Runtime::new();
        runtime.block_on(async move {
            tracing::info!("system thread of t1: {:?}", std::thread::current().id());
            let rt = Runtime::new().unwrap();
            let join_handle = rt.spawn(async move {
                tracing::info!("system thread of t2: {:?}", std::thread::current().id());
                loop { &a; }
            });
            drop(rt);

            let err = join_handle.await.unwrap_err();
            assert!(err.is_cancelled());
        })
    }
```

Another major difference is that we enter the runtime context per task in `madsim`.
https://github.com/madsim-rs/madsim/blob/b7dbec004a161bb7c98b7d3a728a0c0739c1a6fb/madsim/src/sim/task/mod.rs#L279-L280

In tokio however, we always enter the runtime context when we block_on the runtime, so it will always be accessible by spawned tasks. The runtime context is not on a task level.
https://github.com/madsim-rs/madsim/blob/b7dbec004a161bb7c98b7d3a728a0c0739c1a6fb/madsim/src/sim/task/mod.rs#L279-L280

Now consider that destructors for `Runnable` (and hence the drop impl for `A` in our testcase) are ran _after_ it goes out of scope. If we look at the backtrace for the `Drop` test case, we can indeed see it goes out of scope in the next iteration of the loop: https://github.com/madsim-rs/madsim/blob/b7dbec004a161bb7c98b7d3a728a0c0739c1a6fb/madsim/src/sim/task/mod.rs#L315

At this specific part, it is obvious that there is no task context entered! So it clearly explains why there is no task context.

Now the root cause is known, we need to decide how to solve it.

**Comment by BugenZhao** [comment]
By explicitly adding a `drop(runnable)`, we can see that the future is dropped here:

https://github.com/madsim-rs/madsim/blob/9978cf0cd43ce64d1452bc1f3e6c313858516af7/madsim/src/sim/task/mod.rs#L269-L271

Also we don't need a fake `madsim_tokio` runtime to trigger this issue. Simply aborting the task will lead to panic:

```rust
fn runtime_drop_bugen() {
    #[derive(Debug)]
    struct A;
    impl Drop for A {
        fn drop(&mut self) {
            Handle::current().spawn(std::future::pending::<()>());
        }
    }

    let a = A;
    let runtime = madsim::runtime::Runtime::new();
    runtime.block_on(async move {
        let join_handle = madsim::task::spawn(async move { drop(a) });
        join_handle.abort();

        let err = join_handle.await.unwrap_err();
        assert!(err.is_cancelled());
    })
}
```

**Comment by BugenZhao** [comment]
Can we simply call `enter_task` with the `TaskInfo` of the task to be dropped while dropping it? Is there anything blocking us from doing this?

**Comment by kwannoel** [comment]
> Can we simply call `enter_task` with the `TaskInfo` of the task to be dropped while dropping it? Is there anything blocking us from doing this?

You mean inside the `drop` function impl? To manually call `enter_task`, before spawning the thread:
```
    struct A;
    impl Drop for A {
        fn drop(&mut self) {
            enter_task(task_info);
            Handle::current().spawn(std::future::pending::<()>());
        }
    }

```

But how do we get the `task_info`? And seems like this way is kind of adhoc rather than a general fix. We need to look for all occurrences of spawn in drop and add this line.

Or do you mean in the `JoinHandle's` `drop` impl?

**Comment by kwannoel** [comment]
See: https://github.com/madsim-rs/madsim/pull/231 for a solution by @BugenZhao.

Bugen took https://github.com/madsim-rs/madsim/issues/228#issuecomment-2404193538 further, and found that it's actually triggered inside the block which handles cancelled / killed nodes (https://github.com/madsim-rs/madsim/pull/231#discussion_r1794914475). We can abort the future since the node was killed or the task itself was cancelled.
